server:
    port: 8080

spring:
    application:
        name: reconx

    datasource:
        url: jdbc:postgresql://localhost:5432/reconx
        username: postgres
        password: postgres

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true

    flyway:
        enabled: false

    servlet:
        multipart:
            max-file-size: 500MB
            max-request-size: 500MB

    data:
        redis:
            host: localhost
            port: 6379

management:
    endpoints:
        web:
            exposure:
                include: "*"
camel:
    springboot:
        main-run-controller: true
file:
    uploads:
        path: /Users/mac/Documents/iLIFE/PERSONAL/SH/ReconX/uploads/

jwt:
    secret: super-secret-key-super-secret-key